export const INITIALIZE_LOCAL_CART = "INITIALIZE_LOCAL_CART";
export const INITIALIZE_CART = "INITIALIZE_CART";

export const ADD_LOCAL_CART = "ADD_LOCAL_CART";
export const ADD_LOCAL_CART_FULFILLED = "ADD_LOCAL_CART_FULFILLED";
export const ADD_LOCAL_CART_REJECTED = "ADD_LOCAL_CART_REJECTED";

export const REMOVE_LOCAL_CART = "REMOVE_LOCAL_CART";
export const REMOVE_LOCAL_CART_FULFILLED = "REMOVE_LOCAL_CART_FULFILLED";
export const REMOVE_LOCAL_CART_REJECTED = "REMOVE_LOCAL_CART_REJECTED";

export const CHANGE_LOCAL_CART = "CHANGE_LOCAL_CART";
export const CHANGE_LOCAL_CART_FULFILLED = "CHANGE_LOCAL_CART_FULFILLED";
export const CHANGE_LOCAL_CART_REJECTED = "CHANGE_LOCAL_CART_REJECTED";

export const FETCH_SET_CART = "FETCH_SET_CART";
export const FETCH_SET_CART_FULFILLED = "FETCH_SET_CART_FULFILLED";
export const FETCH_SET_CART_REJECTED = "FETCH_SET_CART_REJECTED";

export const FETCH_ADD_CART = "FETCH_ADD_CART";
export const FETCH_ADD_CART_FULFILLED = "FETCH_ADD_CART_FULFILLED";
export const FETCH_ADD_CART_REJECTED = "FETCH_ADD_CART_REJECTED";

export const FETCH_REMOVE_CART = "FETCH_REMOVE_CART";
export const FETCH_REMOVE_CART_FULFILLED = "FETCH_REMOVE_CART_FULFILLED";
export const FETCH_REMOVE_CART_REJECTED = "FETCH_REMOVE_CART_REJECTED";

export const FETCH_CHANGE_CART = "FETCH_CHANGE_CART";
export const FETCH_CHANGE_CART_FULFILLED = "FETCH_CHANGE_CART_FULFILLED";
export const FETCH_CHANGE_CART_REJECTED = "FETCH_CHANGE_CART_REJECTED";

export const SET_ORDER_CART = "SET_ORDER_CART";
