export const INITIALIZE_LOCAL_CART = "INITIALIZE_LOCAL_CART";

export const ADD_LOCAL_CART = "ADD_LOCAL_CART";
export const ADD_LOCAL_CART_FULFILLED = "ADD_LOCAL_CART_FULFILLED";
export const ADD_LOCAL_CART_REJECTED = "ADD_LOCAL_CART_REJECTED";

export const REMOVE_LOCAL_CART = "REMOVE_LOCAL_CART";
export const REMOVE_LOCAL_CART_FULFILLED = "REMOVE_LOCAL_CART_FULFILLED";
export const REMOVE_LOCAL_CART_REJECTED = "REMOVE_LOCAL_CART_REJECTED";
