export const FETCH_SIGNUP = "FETCH_SIGNUP";
export const FETCH_SIGNUP_FULFILLED = "FETCH_SIGNUP_FULFILLED";
export const FETCH_SIGNUP_REJECTED = "FETCH_SIGNUP_REJECTED";

export const FETCH_SIGNIN = "FETCH_SIGNIN";
export const FETCH_SIGNIN_FULFILLED = "FETCH_SIGNIN_FULFILLED";
export const FETCH_SIGNIN_REJECTED = "FETCH_SIGNIN_REJECTED";

export const SIGNOUT = "SIGNOUT";
